var chemEl = {
	azot: { ppm: 1.16211498915, mg: 0.85835912049, pv: 0} 
	ammiak { ppm: 0.6222602661, mg: 1.60304, pv: 43.47826}
	// acetilen { ppm: , mg: , pv: },
	// aceton { ppm: , mg: , pv: }, 
	// benzol { ppm: , mg: , pv: },
	// butan { ppm: , mg: , pv: },
	// vodorod { ppm: , mg: , pv: }, 
	// geksan { ppm: , mg: , pv: },
	// dioksidAzota { ppm: , mg: , pv: },
	// dioksidUgleroda { ppm: , mg: , pv: },
	// izobutan { ppm: , mg: , pv: },
	// kislorod { ppm: , mg: , pv: }, 
	// ksilol { ppm: , mg: , pv: },			        
	// metan { ppm: , mg: , pv: },
	// metanol { ppm: , mg: , pv: },
	// ozon { ppm: , mg: , pv: }, 
	// oksidSery { ppm: , mg: , pv: },
	// oksidUgleroda { ppm: , mg: , pv: }, 
	// oktan { ppm: , mg: , pv: },
	// pentan { ppm: , mg: , pv: },
	// propan { ppm: , mg: , pv: },
	// serovodorod { ppm: , mg: , pv: },
	// sinKislota { ppm: , mg: , pv: },
	// stirol { ppm: , mg: , pv: },
	// toluol { ppm: , mg: , pv: },
	// fenol { ppm: , mg: , pv: },
	// formaldegid { ppm: , mg: , pv: },
	// ftor { ppm: , mg: , pv: },
	// ftorovodorod { ppm: , mg: , pv: },
	// hlor { ppm: , mg: , pv: },
	// hlorovodorod { ppm: , mg: , pv: },
	// etan { ppm: , mg: , pv: },
	// etanol { ppm: , mg: , pv: },
	// etilen  { ppm: , mg: , pv: }
}